### ISSUE TITLE
Adding dates to tasks

### ISSUE THREAD

**Issue by WangAline** [WangAline/Todo_List_Application-Aline_Wang-OCC_1#2]
The application doesn't provide time information on tasks, which makes it difficult to keep track of their chronology. To improve time management and provide users with a better overview, I'd like to add date functionality to tasks.

To do this, I'll need to:
- Modify the data structure to include a date property for each task.
- Update the user interface to display task dates...

**Comment by WangAline** [comment]
@AlexandreCGithub tu peux m'aider?

**Comment by AlexandreCGithub** [comment]
Of course
